server:
  port: 8088
spring:
  application:
    name: gateway
logging:
  level:
    org.springframework: debug

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: core_route
#          uri: lb://core
#          predicates:
#            - Path=/core/**
##          filters:
##            - StripPrefix=1
#        - id: denormal_route
#          uri: lb://denormal
#          predicates:
#            - Path=/zoo/**
##          filters:
##            - StripPrefix=1
